### PR TITLE
Update Python SDK for APIv2

### PR DESCRIPTION
**Pull request by mplooster**
Removed old python examples (they will go elsewhere in the future), and updated the Python SDK to use version 2 of the Diatheke gRPC API.

### CODE REVIEW

**Comment by kapitoshka438** [comment]
@mplooster I was just about to push my PR, because I was working on new Python API as well. 🤦  😄 I don't know if you were aware of this. Anyway, in this case, I can only review this PR and help you if there is something to be done more.
For example, do we want to upgrade to the latest `grpcio-tools` and `googleapis-common-protos` [here](https://github.com/cobaltspeech/sdk-diatheke/blob/0f08a002214011cff51c0ba914646928603a5f7f/Makefile#L47)?

**Comment by mplooster** [comment]
@kapitoshka438 I was not aware that you were also working on it. Sorry! Hopefully what I have here is similar to what you were doing. To answer your question, I don't see a problem with upgrading to the latest `grpcio-tools`. I'm not sure if we are actually using `googleapis-common-protos` for this SDK (I know we are in the cubic SDK, though). It probably wouldn't hurt to update those.

**Comment by kapitoshka438** [comment]
@mplooster `grpcio-tools==1.33.1 googleapis-common-protos==1.52.0` works well. At least I didn't see any issues. I know `gracio-tools` 1.33.2 was released a couple of days ago, but I didn't check it.

**Comment by mplooster** [comment]
Also a related question - does the Makefile fetch the dependencies for building the SDK? Or are those for using the SDK? I ask because we also have the [setup.py](https://github.com/cobaltspeech/sdk-diatheke/blob/master/grpc/py-diatheke/setup.py) file that `pip` can use to install the SDK (including dependencies) (see [here](https://docs.cobaltspeech.com/vui/sdk-diatheke/using-diatheke-sdk/include/#python)). The setup.py file does not specify versions, so I assume it always fetches the latest.

**Comment by kapitoshka438** [comment]
Isn't `grpcio-tools` responsible only for generating `diatheke_pb2_grpc.py` and `diatheke_pb2.py`? I think the SDK packages includes dependency to `grpc`, not `grpcio-tools`. Maybe I'm wrong.

**Comment by mplooster** [comment]
Ah yes, you are right. It is using [`grpcio`](https://github.com/cobaltspeech/sdk-diatheke/blob/master/grpc/py-diatheke/setup.py#L18), not `grpcio-tools`. :+1:

**Comment by mplooster** [comment]
@kapitoshka438 Are there any other changes you would me to make before approving?

**Review by kapitoshka438 — APPROVED** [review]
Me gusta

**Pull request merged**
